name: Build Python Package

on:
  workflow_call:
    outputs:
      package-built:
        description: "Whether the package was successfully built"
        value: ${{ jobs.build.outputs.package-built }}

jobs:
  build:
    name: Build Python distribution packages
    runs-on: ubuntu-latest
    outputs:
      package-built: ${{ steps.build.outputs.package-built }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1

      - name: Set up uv
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
        with:
          enable-cache: true
          python-version: "3.12"
          cache-python: true

      - name: audit dependencies
        run: uvx uv-secure ./uv.lock
        ## パッケージのインストールと、.venvの作成はされないはず...

      # - name: Set up Python environment (default)
      #   run: uv python install

      - name: "INFO: Python and uv version"
        run: |
          uv run python --version
          uv --version

      # - name: Set up Python environment (3.10)
      #   run: uv python install 3.10

      # - name: Configure Git for tests
      #   run: |
      #     git config --global user.name "GitHub Actions"
      #     git config --global user.email "actions@github.com"

      - name: Build distribution packages
        id: build
        run: |
          # uv build
          if uv run poe build; then
            echo "package-built=true" >> "$GITHUB_OUTPUT"
          else
            echo "package-built=false" >> "$GITHUB_OUTPUT"
            exit 1
          fi

      # # Verify that the built packages work correctly
      # - name: Test wheel installation
      #   run: uv run --isolated --no-project --with dist/*.whl whoruv

      # - name: Test source distribution installation
      #   run: uv run --isolated --no-project --with dist/*.tar.gz whoruv

      - name: Upload built packages as artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: python-package-distributions
          path: dist/
          retention-days: 1
