name: Build and Publish to PyPI

on:
  push:
    tags:
      # Regular releases: e.g. v1.2.3
      - "v[0-9]+.[0-9]+.[0-9]+"
      # # Pre-releases: e.g. v1.2.3rc1, v1.2.3b1, v1.2.3a1 (PEP 440 format)
      # - "v[0-9]+.[0-9]+.[0-9]+(a|b|rc)[0-9]+"

concurrency:
  group: publish-pypi-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor
    environment: pypi
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for Trusted Publishing
      contents: read

    steps:
      - name: Build and publish package to TestPyPI
        uses: heiwa4126/reusable-workflows/build-uv-package@d1af8e63af88cd9386f1e6174f748df97fca0647 # v0.0.13
        with:
          checkout: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
