name: Build and Publish to PyPI

on:
  push:
    tags:
      # Regular releases: e.g. v1.2.3
      - "v[0-9]+.[0-9]+.[0-9]+"
      # # Pre-releases: e.g. v1.2.3rc1, v1.2.3b1, v1.2.3a1 (PEP 440 format)
      # - "v[0-9]+.[0-9]+.[0-9]+(a|b|rc)[0-9]+"

concurrency:
  group: publish-pypi-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    if: github.repository_owner == github.actor
    environment: pypi
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for Trusted Publishing
      contents: read

    steps:
      - name: Build and publish package to TestPyPI
        uses: heiwa4126/reusable-workflows/build-uv-package@e1b1d196902211a1f932272f5c21203c573063b5 # v0.0.15
        with:
          checkout: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
